name: Android Check
on:
  workflow_dispatch: # Manual trigger
  pull_request:
    paths-ignore:
      - .gitignore
      - .github/**
      - '**/*_tests/**'
      - CONTRIBUTORS
      - LICENSE
      - NOTICE
      - README.md
      - iphone/**
      - xcode/**
      - docs/**
      - generator/**
      - packaging/**
      - pyhelpers/**
      - qt*/**
      - skin_generator/**
      - tools/**
      - track_generator/**

jobs:
  android-check:
    name: Build Android Debug
    runs-on: ubuntu-latest
    steps:
      - name: Install build tools and dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 100 # enough to get all commits for the current day

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --init --recursive --jobs=$(($(nproc) * 2))

      - name: Configure in Open Source mode
        shell: bash
        run: ./configure.sh

      - name: Set up SDK
        shell: bash
        run: (cd tools/android; ./set_up_android.py --sdk $ANDROID_SDK_ROOT)

      - name: Compile
        shell: bash
        working-directory: android
        run: |
          cmake --version
          ninja --version
          ./gradlew -Parm64 assembleWebDebug

      - name: Upload arm64-v8a debug apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-arm64-v8a-debug
          path: android/build/outputs/apk/web/debug/OrganicMaps-*-web-debug.apk
          if-no-files-found: error

  android-check-metadata:
    name: Check app metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check metadata
        run: ./tools/python/check_store_metadata.py android
