name: Sync Fork

on:
  schedule:
    - cron: '35 4 * * *' # every day 4:35
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      # - uses: tgymnich/fork-sync@v1.6.3
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: untimished
          base: master
          head: master
